language: node_js
node_js:
  - "8.9.4"
install:
  - yarn install
env:
  - DB_TYPE="sqlite" DB_DATABASE="./mydb.sql" DB_LOGGING=false
scripts:
  - npm start build
  - npm start test
  - npm start test.integration
  - npm start test.e2e
notifications:
  email: false
